spring.application.name=job-listing
spring.data.mongodb.uri=mongodb://user:root@akash-shard-00-00.iv258.mongodb.net:27017,akash-shard-00-01.iv258.mongodb.net:27017,akash-shard-00-02.iv258.mongodb.net:27017/?replicaSet=atlas-n2ck34-shard-0&ssl=true&authSource=admin&retryWrites=true&w=majority&appName=akash
spring.data.mongodb.database=JobPortal

server.servlet.session.persistent=false
